# Generated by Django 6.0.2 on 2026-02-27 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_alter_laborder_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laborder',
            options={'verbose_name': 'orden de laboratorio', 'verbose_name_plural': 'órdenes de laboratorio'},
        ),
        migrations.AlterModelOptions(
            name='labtest',
            options={'verbose_name': 'prueba de laboratorio', 'verbose_name_plural': 'pruebas de laboratorio'},
        ),
    ]
