# Generated by Django 6.0.2 on 2026-02-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_alter_laborder_options_alter_labtest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laborder',
            name='status',
            field=models.CharField(choices=[('CREATED', 'CREATED'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED')], default='PROCESSING', max_length=20),
        ),
    ]
